"""Seed matters and transcripts for the HakiScribe demo desk.

Kept free of storage imports so ``seed_demo.py`` can reuse the same catalog
against a remote API without booting the local store.
"""

from __future__ import annotations

from typing import Any

SHOWCASE_TITLE = "Client meeting — Wanjiru Holdings, defective works at Kilimani site"
# Primary multilingual hearing demo (seeded as Sahara legal refine; title blends with library).
SAHARA_DEMO_TITLE = "Court proceeding — Milimani Commercial Court, Wanjiru Holdings lease arrears"

# Multilingual / code-switch seeds mixed through existing matters (primary first).
SAHARA_DEMO_TITLES: list[str] = [
    SAHARA_DEMO_TITLE,
    "Voice memo — Wanjiru Holdings, Kilimani remedial works follow-up",
    "Client briefing — Otieno, ELRC directions after mention",
    "Client call — Coastal Sacco, Nyali statutory notice plan",
    "Follow-up intake — Githunguri succession, revocation advice",
    "Site briefing — Karanja & Sons, Westlands distress after lock-out",
    "Client intake — Bello Trading, Kano warehouse lease dispute",
    "Client call — Adeyemi & Co, Lagos employment notice review",
    "Mention notes — Dlamini, Johannesburg eviction defence",
]


def _seg(
    speaker: str,
    text: str,
    start_s: float,
    dur_s: float = 6,
    *,
    provider: str | None = None,
    source_extra: dict[str, Any] | None = None,
) -> dict:
    segment: dict[str, Any] = {
        "speaker": speaker,
        "text": text,
        "start_ms": int(start_s * 1000),
        "end_ms": int((start_s + dur_s) * 1000),
        "confidence": 0.94,
    }
    if provider:
        raw = {"provider": provider}
        if source_extra:
            raw.update(source_extra)
        segment["source_raw"] = raw
    return segment


def _sahara(
    speaker: str,
    text: str,
    start_s: float,
    dur_s: float = 6,
    *,
    court: bool = False,
) -> dict:
    extra: dict[str, Any] = {"mode": "file_category_legal"}
    if court:
        extra["get_legal_court_hearing"] = True
    return _seg(speaker, text, start_s, dur_s, provider="sahara", source_extra=extra)


MATTERS: list[dict[str, str]] = [
    {"client_name": "Wanjiru Holdings Ltd", "matter_name": "Wanjiru Holdings v. Sarova Contractors — construction defect"},
    {"client_name": "Achieng' Otieno", "matter_name": "Otieno — employment termination claim"},
    {"client_name": "Mombasa Coastal Sacco", "matter_name": "Coastal Sacco — loan recovery portfolio"},
    {"client_name": "Barclays", "matter_name": "Barclays vs. Apex Logistics"},
    {"client_name": "Apex Logistics (EA) Limited", "matter_name": "Barclays vs. Apex Logistics — facility default"},
    {"client_name": "Githunguri Family Estate", "matter_name": "Estate of the late Njoroge Kamau — succession"},
    {"client_name": "Karanja & Sons Ltd", "matter_name": "Karanja & Sons v. Riverside Properties — irregular distress"},
    {
        "client_name": "Kamau Enterprises Ltd",
        "matter_name": "Wanjiru Holdings Ltd v. Kamau Enterprises Ltd — lease arrears (Milimani CS 204/2026)",
    },
    {"client_name": "Bello Trading Ltd", "matter_name": "Bello Trading v. Northern Logistics — warehouse lease (Kano)"},
    {"client_name": "Adeyemi & Co", "matter_name": "Adeyemi — wrongful dismissal claim (Lagos)"},
    {"client_name": "Thandi Dlamini", "matter_name": "Dlamini — residential eviction defence (Johannesburg)"},
]

SESSIONS: list[dict[str, Any]] = [
    {
        "title": SHOWCASE_TITLE,
        "source": "omi",
        "language_hint": "code-switch",
        "client_name": "Wanjiru Holdings Ltd",
        "speakers": {"Speaker 1": "Adv. Naomi Kariuki", "Speaker 2": "James Wanjiru"},
        "flags": [
            {"at_ms": 41000, "label": "Payment withheld — key fact"},
            {"at_ms": 77000, "label": "Deadline for demand letter"},
        ],
        "segments": [
            _seg("Speaker 1", "Thanks for coming in, James. Before we start — this conversation is privileged. Take me through what happened at the Kilimani site.", 0, 9),
            _seg("Speaker 2", "Sarova Contractors were meant to complete the slab works by the fifteenth of June. By July the slab had visible cracking on the second floor.", 9, 11),
            _seg("Speaker 1", "Did you raise it with them in writing?", 20, 4),
            _seg("Speaker 2", "Yes, twice. Email on the second of July, then a WhatsApp on the eighteenth. They said they would send an engineer, hakuna kitu ilifanyika.", 24, 12),
            _seg("Speaker 1", "And the contract sum? What has been paid so far?", 36, 5),
            _seg("Speaker 2", "Contract was eighteen million shillings. We have paid twelve point six million. We withheld the balance after the cracking.", 41, 11),
            _seg("Speaker 2", "The structural engineer, Eng. Mutiso, says remedial works will cost about four point two million.", 52, 9),
            _seg("Speaker 1", "Good. That gives us a quantified loss. I want to send a formal demand letter to Sarova Contractors before we consider arbitration under clause 41.", 61, 13),
            _seg("Speaker 2", "How long do they get?", 74, 3),
            _seg("Speaker 1", "Twenty-one days. If they don't respond we file a notice of arbitration. Let's also diarise a follow-up meeting on the third of October at ten in the morning.", 77, 14),
            _seg("Speaker 2", "That works. Also, please keep the bit about my partner's tax position out of anything you write.", 91, 8),
            _seg("Speaker 1", "Noted — that stays off the record. I'll get the demand letter to you for review by Friday.", 99, 8),
            _seg("Speaker 2", "Asante, Naomi. I will send Mutiso's report and the payment schedule this afternoon.", 107, 8),
            _seg("Speaker 1", "Perfect. Once I have those, the letter goes out. Talk tomorrow if anything else comes up.", 115, 8),
        ],
        "redact_indexes": [10],
        "generate": True,
    },
    {
        "title": "Voice memo — Wanjiru Holdings, Kilimani remedial works follow-up",
        "source": "omi",
        "language_hint": "multilingual",
        "detected_language": "code-switch",
        "client_name": "Wanjiru Holdings Ltd",
        "speakers": {"Speaker 1": "Adv. Naomi Kariuki"},
        "flags": [
            {"at_ms": 0, "label": "Remedial cost — KES 4.2M"},
            {"at_ms": 24000, "label": "Seven-day follow-up before arbitration"},
        ],
        "segments": [
            _sahara(
                "Speaker 1",
                "Voice memo for the Wanjiru Holdings file. Leo nilitembelea Kilimani site with Eng. Mutiso. He confirms remedial works at about four point two million shillings — cracked slab on the second floor, same as July.",
                0,
                14,
            ),
            _sahara(
                "Speaker 1",
                "Sarova bado haijalipa, and they have not answered our demand of the twelfth of August. Fourteen days zimeisha without a substantive reply.",
                14,
                10,
            ),
            _sahara(
                "Speaker 1",
                "Tafadhali draft a follow-up letter giving them seven more days. If they still ignore us, we issue the arbitration notice under clause forty-one of the contract.",
                24,
                12,
            ),
            _sahara(
                "Speaker 1",
                "Attach Mutiso's report and the payment schedule showing twelve point six million already paid against the eighteen million contract sum. Make clear the balance remains withheld for cause.",
                36,
                13,
            ),
            _sahara(
                "Speaker 1",
                "Diarise a call with James Wanjiru on Friday at nine o'clock. I want him to approve the follow-up letter before it goes out.",
                49,
                10,
            ),
            _sahara(
                "Speaker 1",
                "Keep the partner tax discussion completely off this memo and off any letter — that stays privileged. End of memo.",
                59,
                9,
            ),
        ],
        "redact_indexes": [5],
        "generate": True,
    },
    {
        "title": "Court proceeding — Employment & Labour Relations Court, Otieno termination",
        "source": "mic",
        "language_hint": "en",
        "client_name": "Achieng' Otieno",
        "speakers": {
            "Speaker 1": "Hon. Justice Mwangi",
            "Speaker 2": "Adv. Naomi Kariuki",
            "Speaker 3": "Adv. Peter Ochieng",
        },
        "flags": [
            {"at_ms": 16000, "label": "Summary dismissal — no show cause"},
            {"at_ms": 48000, "label": "Court directions — filing dates"},
        ],
        "segments": [
            _seg("Speaker 1", "Cause number forty-two of this year, Achieng' Otieno versus Bidii Logistics Limited. Appearances please.", 0, 9),
            _seg("Speaker 2", "Kariuki for the claimant, my lord.", 9, 4),
            _seg("Speaker 3", "Ochieng' for the respondent.", 13, 3),
            _seg(
                "Speaker 2",
                "My lord, the claimant was summarily dismissed on the ninth of March without a show cause letter and without a hearing, contrary to section forty-one of the Employment Act.",
                16,
                14,
            ),
            _seg(
                "Speaker 2",
                "She seeks reinstatement, or in the alternative compensation for unfair termination, unpaid February and March salary, and a certificate of service.",
                30,
                11,
            ),
            _seg(
                "Speaker 3",
                "My lord, the respondent's position is that the claimant abandoned duty for eleven consecutive days. We dispute that procedure was not followed.",
                41,
                11,
            ),
            _seg("Speaker 1", "Counsel, has the respondent filed a replying affidavit?", 52, 5),
            _seg("Speaker 3", "Not yet, my lord. We seek fourteen days.", 57, 4),
            _seg(
                "Speaker 1",
                "The respondent shall file and serve a replying affidavit within fourteen days. The claimant may file a supplementary affidavit within seven days thereafter.",
                61,
                13,
            ),
            _seg(
                "Speaker 1",
                "Mention on the twenty-eighth of October at nine o'clock for further directions. Highlighting of submissions thereafter. Costs in the cause.",
                74,
                12,
            ),
            _seg("Speaker 2", "Much obliged, my lord.", 86, 3),
            _seg("Speaker 3", "As the court pleases.", 89, 3),
            _seg("Speaker 1", "That is the order of the court. Next matter.", 92, 5),
        ],
        "redact_indexes": [],
        "generate": True,
    },
    {
        "title": "Client briefing — Otieno, ELRC directions after mention",
        "source": "mic",
        "language_hint": "multilingual",
        "detected_language": "code-switch",
        "client_name": "Achieng' Otieno",
        "speakers": {"Speaker 1": "Adv. Naomi Kariuki", "Speaker 2": "Achieng' Otieno"},
        "flags": [
            {"at_ms": 0, "label": "Mention — 28 October"},
            {"at_ms": 33000, "label": "Payslips and dismissal letter by Friday"},
        ],
        "segments": [
            _sahara(
                "Speaker 1",
                "Achieng', asante kwa kuja. Mahakama imeweka mention on the twenty-eighth of October at nine. The respondent, Bidii Logistics, must file a replying affidavit within fourteen days.",
                0,
                13,
                court=True,
            ),
            _sahara(
                "Speaker 2",
                "Je, hiyo ina-mean nini kwa case yangu? Will I get my salary for February and March, and can I go back to work?",
                13,
                10,
            ),
            _sahara(
                "Speaker 1",
                "It means we keep pressure on them. We asked for reinstatement or compensation for unfair dismissal. Nataka ulete payslips, the dismissal letter, and any WhatsApp with your supervisor by Friday.",
                23,
                14,
            ),
            _sahara(
                "Speaker 2",
                "Sawa, nitawaleta. They said I abandoned duty, but I had sent medical notes. Do I need more witnesses?",
                37,
                10,
            ),
            _sahara(
                "Speaker 1",
                "If they raise abandonment again, we file a supplementary affidavit with those notes and a colleague who can confirm you reported sick. Tutafanya follow-up call after they serve their papers.",
                47,
                13,
            ),
            _sahara(
                "Speaker 2",
                "Also, my sister helped me with school fees when I was unpaid — that bit is private, usiiandike kwenye letter to the court or to Bidii.",
                60,
                11,
            ),
            _sahara(
                "Speaker 1",
                "Noted, that stays off the record. I will draft a short client update letter summarising today's directions and diarise the twenty-eighth mention.",
                71,
                11,
            ),
            _sahara(
                "Speaker 2",
                "Asante sana, advocate. Niko ready for Friday.",
                82,
                5,
            ),
            _sahara(
                "Speaker 1",
                "Good. Bring the documents to chambers or send scans. We will be ready when Bidii files.",
                87,
                8,
            ),
        ],
        "redact_indexes": [5],
        "generate": True,
    },
    {
        "title": "Client call — Mombasa Coastal Sacco, defaulted loan recovery strategy",
        "source": "omi",
        "language_hint": "code-switch",
        "client_name": "Mombasa Coastal Sacco",
        "speakers": {"Speaker 1": "Adv. Naomi Kariuki", "Speaker 2": "Fatuma Said (CEO, Coastal Sacco)"},
        "flags": [
            {"at_ms": 33000, "label": "Statutory notice timeline"},
            {"at_ms": 66000, "label": "Review meeting — 20 September"},
        ],
        "segments": [
            _seg("Speaker 1", "Fatuma, you mentioned three accounts in default. Give me the worst one first.", 0, 7),
            _seg(
                "Speaker 2",
                "Mwakio Enterprises. Four point eight million outstanding, last payment was in November. Security is a title in Nyali, LR number Mombasa slash Block Twelve slash three four one.",
                7,
                15,
            ),
            _seg("Speaker 1", "Have you issued a statutory notice under section ninety of the Land Act?", 22, 6),
            _seg("Speaker 2", "Hapana, not yet. We only sent internal reminder letters and one board chase-up.", 28, 7),
            _seg(
                "Speaker 1",
                "Then we start there — a three months' statutory notice, then the forty days' notification before sale. I'll prepare the section ninety notice this week.",
                35,
                13,
            ),
            _seg("Speaker 2", "And the other two? Kadzo Traders is about nine hundred thousand, unsecured. Hassan Supply is one point two million with a personal guarantee.", 48, 12),
            _seg(
                "Speaker 1",
                "For unsecured, a demand then a plaint in the Magistrate's Court. For Hassan we enforce the guarantee in parallel. Let's open one recovery matter for the Sacco portfolio so everything sits in one file.",
                60,
                14,
            ),
            _seg("Speaker 2", "Please do. Can we meet on the twentieth of September at two p.m. to review all three?", 74, 8),
            _seg("Speaker 1", "Twentieth at two works. I'll circulate a status note before then, with draft notices attached.", 82, 9),
            _seg("Speaker 2", "One caution — keep the board's internal provisioning numbers out of anything external.", 91, 8),
            _seg("Speaker 1", "Understood. That stays privileged. I will only use the contractual outstanding figures in the notices.", 99, 9),
            _seg("Speaker 2", "Asante, Naomi. Send me the drafts for Mwakio first.", 108, 5),
            _seg("Speaker 1", "You will have them by Wednesday. Talk then.", 113, 5),
        ],
        "redact_indexes": [9],
        "generate": True,
    },
    {
        "title": "Client call — Coastal Sacco, Nyali statutory notice plan",
        "source": "omi",
        "language_hint": "multilingual",
        "detected_language": "code-switch",
        "client_name": "Mombasa Coastal Sacco",
        "speakers": {"Speaker 1": "Adv. Naomi Kariuki", "Speaker 2": "Fatuma Said (CEO, Coastal Sacco)"},
        "flags": [
            {"at_ms": 12000, "label": "Section 90 notice — Mwakio"},
            {"at_ms": 45000, "label": "Portfolio review — 20 September 2 p.m."},
        ],
        "segments": [
            _sahara(
                "Speaker 2",
                "Naomi, asante kwa kupiga. Mwakio bado hajalipa. Four point eight million is outstanding since November. Title iko Nyali, LR Mombasa Block Twelve slash three four one.",
                0,
                13,
            ),
            _sahara(
                "Speaker 1",
                "Tutaanza na section ninety statutory notice this week. After three months, the forty days' notification before sale. Hapana shortcuts — Land Act process lazima ifuatwe.",
                13,
                13,
            ),
            _sahara(
                "Speaker 2",
                "Na Kadzo Traders? Nine hundred thousand, unsecured — tunaweza file plaint Mombasa Magistrate Court? Hassan Supply also, one point two million with a personal guarantee.",
                26,
                12,
            ),
            _sahara(
                "Speaker 1",
                "Yes. Demand then plaint for Kadzo. For Hassan we sue on the guarantee as well. I will open one recovery matter for the portfolio so all three sit together.",
                38,
                12,
            ),
            _sahara(
                "Speaker 1",
                "I will draft the Mwakio notice, circulate a short status note, and calendar our review on the twentieth of September at two p.m.",
                50,
                11,
            ),
            _sahara(
                "Speaker 2",
                "Poa. Please keep the board's internal provisioning figure off anything you send outside — that one is sensitive.",
                61,
                9,
            ),
            _sahara(
                "Speaker 1",
                "Understood — that stays privileged. Notices will only show contractual outstanding and the security particulars.",
                70,
                9,
            ),
            _sahara(
                "Speaker 2",
                "Asante. Send Mwakio draft first, then Kadzo and Hassan demands.",
                79,
                7,
            ),
            _sahara(
                "Speaker 1",
                "By Wednesday. If Mwakio pays anything before then, niambie immediately so we pause the notice.",
                86,
                8,
            ),
        ],
        "redact_indexes": [5],
        "generate": True,
    },
    {
        "title": "Intake — new client, land succession dispute in Kiambu",
        "source": "mic",
        "language_hint": "code-switch",
        "client_name": "Githunguri Family Estate",
        "speakers": {"Speaker 1": "Adv. Naomi Kariuki", "Speaker 2": "Grace Njeri"},
        "flags": [
            {"at_ms": 35000, "label": "Revocation under section 76"},
            {"at_ms": 53000, "label": "Limitation concern"},
        ],
        "segments": [
            _seg("Speaker 1", "Grace, thank you for coming in. Tell me about the land and who is currently on the title.", 0, 7),
            _seg(
                "Speaker 2",
                "My late father's parcel in Kiambu, Githunguri. He died in twenty-nineteen. My brother obtained letters of administration and transferred two acres to himself.",
                7,
                14,
            ),
            _seg("Speaker 1", "Were you listed as a beneficiary in the petition?", 21, 5),
            _seg(
                "Speaker 2",
                "No. He said I was married so sitakuwa na haki. My mother and two sisters were also left out. None of us were served.",
                26,
                11,
            ),
            _seg(
                "Speaker 1",
                "That's not the law. Under the Law of Succession Act a married daughter remains a beneficiary. We can apply to revoke the grant under section seventy-six for concealment of material facts.",
                37,
                15,
            ),
            _seg("Speaker 2", "Is it too late? It's been a while since the transfer.", 52, 5),
            _seg(
                "Speaker 1",
                "Revocation isn't strictly time-barred where the grant was obtained by concealment, but we should move quickly before further dealings. Bring the death certificate, the grant, and the green card search.",
                57,
                15,
            ),
            _seg(
                "Speaker 2",
                "I'll get them next week. There is also a family meeting planned about our sister who lives abroad — that discussion should stay private.",
                72,
                10,
            ),
            _seg(
                "Speaker 1",
                "Understood, that stays off the record. I will open a succession matter, draft a first advice letter, and we meet again once documents are in.",
                82,
                12,
            ),
            _seg("Speaker 2", "Asante. I will call when I have the green card.", 94, 5),
            _seg("Speaker 1", "Do that. Meanwhile avoid any further family transfers of that land.", 99, 7),
        ],
        "redact_indexes": [7],
        "generate": True,
    },
    {
        "title": "Follow-up intake — Githunguri succession, revocation advice",
        "source": "mic",
        "language_hint": "multilingual",
        "detected_language": "code-switch",
        "client_name": "Githunguri Family Estate",
        "speakers": {"Speaker 1": "Adv. Naomi Kariuki", "Speaker 2": "Grace Njeri"},
        "flags": [
            {"at_ms": 13000, "label": "Revocation under s.76"},
            {"at_ms": 48000, "label": "Documents due next week"},
        ],
        "segments": [
            _sahara(
                "Speaker 2",
                "Dada Naomi, nimerudi as you asked. Brother alichukua grant bila majina yetu. He transferred two acres in Githunguri to himself after baba died in twenty-nineteen.",
                0,
                13,
            ),
            _sahara(
                "Speaker 1",
                "Under the Law of Succession Act, a married daughter remains a beneficiary. Sitakuwa na haki is not the law. We apply to revoke the grant under section seventy-six for concealment.",
                13,
                13,
            ),
            _sahara(
                "Speaker 2",
                "Mama and my two sisters were also left out. We were never served with the petition. Is it too late to reverse the transfer?",
                26,
                10,
            ),
            _sahara(
                "Speaker 1",
                "Revocation is available where the grant was obtained by concealment, but we must move quickly before more dealings. Once the grant falls, the transfer can be challenged.",
                36,
                12,
            ),
            _sahara(
                "Speaker 1",
                "Lete death certificate, the grant, the green card search, and any SMS or letter where he said married daughters have no share. Next week is fine if you move this week.",
                48,
                13,
            ),
            _sahara(
                "Speaker 2",
                "Sawa. One thing — the family meeting about our sister abroad and how we support her is private. Usiiweke kwenye affidavit au advice letter.",
                61,
                11,
            ),
            _sahara(
                "Speaker 1",
                "That stays off the record. I will open a succession matter today and draft a first advice letter outlining the revocation path and the documents we need.",
                72,
                12,
            ),
            _sahara(
                "Speaker 2",
                "Asante sana. Nitakupigia Friday once I have the green card from Kiambu lands.",
                84,
                7,
            ),
            _sahara(
                "Speaker 1",
                "Perfect. Until then, hakuna further signing on that title. We protect the estate first.",
                91,
                8,
            ),
        ],
        "redact_indexes": [5],
        "generate": True,
    },
    {
        "title": "Case conference — Barclays vs. Apex Logistics, facility default and charge enforcement",
        "source": "mic",
        "language_hint": "en",
        "client_name": "Barclays",
        "speakers": {
            "Speaker 1": "Adv. Naomi Kariuki",
            "Speaker 2": "Susan Mbugua (Head of Recoveries, Barclays)",
            "Speaker 3": "Adv. Brian Kiptoo",
        },
        "flags": [
            {"at_ms": 35000, "label": "Statutory notice not yet issued"},
            {"at_ms": 91000, "label": "Ruling date — Milimani 12 October"},
        ],
        "segments": [
            _seg(
                "Speaker 2",
                "Naomi, the Apex Logistics facility is now firmly in default. The outstanding is one hundred and forty million shillings as at the end of last month.",
                0,
                12,
            ),
            _seg("Speaker 1", "And the security held by the bank?", 12, 4),
            _seg(
                "Speaker 2",
                "A legal charge over the Industrial Area godown, L.R. number two zero nine slash one one four three, plus a debenture over the fleet.",
                16,
                12,
            ),
            _seg("Speaker 1", "Has the bank issued a statutory notice under section ninety of the Land Act?", 28, 7),
            _seg(
                "Speaker 2",
                "Hapana, not yet. Credit wanted a restructure first, but Apex have missed the last three instalments and the restructure talks collapsed.",
                35,
                11,
            ),
            _seg(
                "Speaker 1",
                "Then the sequence is a formal demand, then section ninety notice, then the forty days' notification before sale. We should also file a plaint in the Milimani Commercial Court for the unsecured portion.",
                46,
                15,
            ),
            _seg("Speaker 3", "Apex have already written threatening an injunction over the godown if we move to sell.", 61, 8),
            _seg(
                "Speaker 1",
                "Expected. We prepare a replying affidavit in advance so we are not caught flat-footed if they move ex parte. Brian, please start that draft this week.",
                69,
                12,
            ),
            _seg("Speaker 2", "The bank also wants a formal demand letter on record before any of that.", 81, 7),
            _seg(
                "Speaker 1",
                "Agreed — demand letter first, fourteen days to remedy, then the statutory notice. Ruling on the pending application in Milimani is on the twelfth of October at eleven.",
                88,
                14,
            ),
            _seg("Speaker 2", "One more thing — keep the internal provisioning figure out of anything filed or sent to Apex.", 102, 9),
            _seg(
                "Speaker 1",
                "Understood, that stays off the record. I will circulate the demand draft and a short litigation plan by Wednesday.",
                111,
                10,
            ),
            _seg("Speaker 3", "I will diarise the twelfth and start the replying affidavit skeleton today.", 121, 7),
            _seg("Speaker 2", "Good. Let's reconvene after the demand goes out.", 128, 5),
        ],
        "redact_indexes": [10],
        "generate": True,
    },
    {
        "title": "Client meeting — Karanja & Sons, commercial lease dispute at Westlands",
        "source": "omi",
        "language_hint": "code-switch",
        "client_name": "Karanja & Sons Ltd",
        "speakers": {
            "Speaker 1": "Adv. Naomi Kariuki",
            "Speaker 2": "Peter Karanja (Director, Karanja & Sons Ltd)",
        },
        "flags": [
            {"at_ms": 46000, "label": "Distress for rent — key exposure"},
            {"at_ms": 77000, "label": "Affidavit signing — 25 September"},
        ],
        "segments": [
            _seg("Speaker 1", "Peter, take me through what the landlord has done at the Westlands premises.", 0, 7),
            _seg(
                "Speaker 2",
                "Riverside Properties Limited levied distress last Thursday. They locked our warehouse and took stock worth about six million shillings.",
                7,
                13,
            ),
            _seg("Speaker 1", "Are you in arrears?", 20, 3),
            _seg(
                "Speaker 2",
                "Three months, about two point four million. But the lease says they must give thirty days' notice before any distress. Hapana notice ilitolewa.",
                23,
                12,
            ),
            _seg("Speaker 1", "Did they serve that notice in writing?", 35, 4),
            _seg(
                "Speaker 2",
                "Nothing in writing. We only got a phone call from the caretaker on the morning of the lock-out. Inventory was taken without our representative.",
                39,
                11,
            ),
            _seg(
                "Speaker 1",
                "Then the distress is irregular. We can move the Business Premises Rent Tribunal for a reference and an interim order restoring possession, and restrain sale of the goods.",
                50,
                14,
            ),
            _seg("Speaker 2", "How fast can we move? Stock is perishable on some lines.", 64, 6),
            _seg(
                "Speaker 1",
                "We file the reference this week and seek an interim order within seven days. I will also write a demand letter to Riverside for the value of the goods taken and unlawful lock-out.",
                70,
                14,
            ),
            _seg(
                "Speaker 2",
                "Please do. Can we meet on the twenty-fifth of September at eleven to sign the affidavit?",
                84,
                8,
            ),
            _seg(
                "Speaker 1",
                "Twenty-fifth at eleven works. Bring the lease, the rent schedule, photographs of the lock-out, and a stock list with values.",
                92,
                11,
            ),
            _seg(
                "Speaker 2",
                "There was also a side cash sale conversation with a neighbour — keep that off any paper we file.",
                103,
                8,
            ),
            _seg(
                "Speaker 1",
                "Privileged. It will not appear in the reference or the demand. I will send you a draft affidavit by Monday.",
                111,
                9,
            ),
        ],
        "redact_indexes": [11],
        "generate": True,
    },
    {
        "title": "Site briefing — Karanja & Sons, Westlands distress after lock-out",
        "source": "omi",
        "language_hint": "multilingual",
        "detected_language": "code-switch",
        "client_name": "Karanja & Sons Ltd",
        "speakers": {
            "Speaker 1": "Adv. Naomi Kariuki",
            "Speaker 2": "Peter Karanja (Director, Karanja & Sons Ltd)",
        },
        "flags": [
            {"at_ms": 12000, "label": "Irregular distress — BPRT"},
            {"at_ms": 48000, "label": "Interim order within seven days"},
        ],
        "segments": [
            _sahara(
                "Speaker 2",
                "Naomi, niko site. Landlord alilock warehouse jana asubuhi. Stock worth about six million. Hapana written notice — only a call from the caretaker, then padlocks.",
                0,
                13,
            ),
            _sahara(
                "Speaker 1",
                "Lease ina-require thirty days' notice before distress. Without it, the levy is irregular. Tutaenda Business Premises Rent Tribunal for a reference and interim restoration.",
                13,
                13,
            ),
            _sahara(
                "Speaker 2",
                "Arrears ni three months, two point four million — tuna-admit that, but process ilikuwa wrong. Inventory was done without us. How fast can we move?",
                26,
                12,
            ),
            _sahara(
                "Speaker 1",
                "We file this week and seek an interim order within seven days restraining sale and restoring access. I will also demand Riverside for the value of goods taken and the lock-out loss.",
                38,
                14,
            ),
            _sahara(
                "Speaker 1",
                "Meeting twenty-fifth of September at eleven to sign the supporting affidavit. Lete lease, rent schedule, photos, and the stock valuation.",
                52,
                11,
            ),
            _sahara(
                "Speaker 2",
                "Poa. Keep the conversation about the side cash sale with the neighbour off paper — that one is sensitive for the business.",
                63,
                10,
            ),
            _sahara(
                "Speaker 1",
                "Privileged. It will not go in the tribunal papers. I will draft the reference and demand and send both before the signing meeting.",
                73,
                11,
            ),
            _sahara(
                "Speaker 2",
                "Asante. Nitakuwa pale twenty-fifth. Staff wako nje for now — we need that interim order.",
                84,
                8,
            ),
            _sahara(
                "Speaker 1",
                "Understood. File goes in this week. Sit tight and do not attempt re-entry without the order.",
                92,
                8,
            ),
        ],
        "redact_indexes": [5],
        "generate": True,
    },
    {
        "title": "Court proceeding — Milimani Commercial Court, Riverside Properties injunction application",
        "source": "mic",
        "language_hint": "en",
        "client_name": "Karanja & Sons Ltd",
        "speakers": {
            "Speaker 1": "Hon. Lady Justice Wambui",
            "Speaker 2": "Adv. Naomi Kariuki",
            "Speaker 3": "Adv. Brian Kiptoo",
        },
        "flags": [
            {"at_ms": 51000, "label": "Interim orders granted"},
            {"at_ms": 78000, "label": "Mention — 12 October"},
        ],
        "segments": [
            _seg(
                "Speaker 1",
                "Civil suit number three one seven of this year, Karanja and Sons Limited versus Riverside Properties Limited. Appearances.",
                0,
                10,
            ),
            _seg("Speaker 2", "Kariuki for the applicant, my lady.", 10, 4),
            _seg("Speaker 3", "Kiptoo for the respondent.", 14, 3),
            _seg(
                "Speaker 2",
                "My lady, the respondent levied distress on the eleventh of September without the thirty days' notice required under the lease and without a court process. Stock valued at about six million was removed.",
                17,
                15,
            ),
            _seg(
                "Speaker 2",
                "We seek interim orders restraining sale or disposal of the attached goods and restoring the applicant to possession pending inter partes hearing.",
                32,
                11,
            ),
            _seg(
                "Speaker 3",
                "My lady, the applicant is in arrears of two point four million shillings and the respondent acted within its contractual right of re-entry.",
                43,
                11,
            ),
            _seg("Speaker 1", "Counsel for the respondent, was any notice served in writing before the distress?", 54, 7),
            _seg("Speaker 3", "Not in writing, my lady. There was a telephone communication.", 61, 5),
            _seg(
                "Speaker 1",
                "The court grants an interim order restraining the respondent from selling or disposing of the attached goods pending the hearing of the application inter partes. Possession of the premises is restored to the applicant on terms that rent arrears continue to accrue.",
                66,
                16,
            ),
            _seg(
                "Speaker 1",
                "The respondent shall file a replying affidavit within fourteen days. The applicant may file a supplementary affidavit within seven days thereafter.",
                82,
                12,
            ),
            _seg(
                "Speaker 1",
                "Mention on the twelfth of October at eleven o'clock for directions on the main suit. Costs in the cause.",
                94,
                10,
            ),
            _seg("Speaker 2", "Much obliged, my lady.", 104, 3),
            _seg("Speaker 3", "As the court pleases.", 107, 3),
            _seg("Speaker 1", "That is the order. Court rises for a short break.", 110, 5),
        ],
        "redact_indexes": [],
        "generate": True,
    },
    {
        "title": SAHARA_DEMO_TITLE,
        "source": "mic",
        "language_hint": "multilingual",
        "detected_language": "code-switch",
        "client_name": "Kamau Enterprises Ltd",
        "speakers": {
            "Speaker 1": "Hon. Lady Justice Wambui",
            "Speaker 2": "Adv. Naomi Kariuki",
            "Speaker 3": "Adv. Peter Ochieng",
        },
        "flags": [
            {"at_ms": 14000, "label": "Arrears quantified — KES 450,000"},
            {"at_ms": 78000, "label": "Hearing date fixed — 14 April 2026"},
        ],
        "segments": [
            _sahara(
                "Speaker 1",
                "Civil Suit number two zero four of twenty twenty-six, Wanjiru Holdings Limited versus Kamau Enterprises Limited, Milimani Commercial Court. Appearances please.",
                0,
                12,
                court=True,
            ),
            _sahara(
                "Speaker 2",
                "Kariuki for the plaintiff, my lady.",
                12,
                3,
                court=True,
            ),
            _sahara(
                "Speaker 3",
                "Ochieng for the defendant, my lady.",
                15,
                3,
                court=True,
            ),
            _sahara(
                "Speaker 2",
                "Mheshimiwa, the claim is for lease arrears of KES four hundred and fifty thousand under the lease agreement signed in March twenty twenty-four for the Industrial Area unit.",
                18,
                13,
                court=True,
            ),
            _sahara(
                "Speaker 2",
                "Demand letter dated the twelfth of August was served. Hapana response within the fourteen days granted. We request a hearing within thirty days and an interim order for deposit of ongoing rent.",
                31,
                14,
                court=True,
            ),
            _sahara(
                "Speaker 3",
                "My lady, hatutaki kucheleweshwa tena, but we dispute the quantum. Part of the alleged arrears relates to service charge that was never particularised. We seek fourteen days to file a replying affidavit.",
                45,
                14,
                court=True,
            ),
            _sahara(
                "Speaker 1",
                "Counsel for the plaintiff, is the four hundred and fifty thousand limited to rent, or does it include service charge?",
                59,
                9,
                court=True,
            ),
            _sahara(
                "Speaker 2",
                "Primarily rent, my lady. We will particularise service charge in a supplementary affidavit if the court so directs.",
                68,
                9,
                court=True,
            ),
            _sahara(
                "Speaker 1",
                "The court notes the arrears claimed at KES four hundred and fifty thousand. The defendant shall file and serve a replying affidavit within fourteen days. The plaintiff may file a supplementary affidavit within seven days thereafter.",
                77,
                15,
                court=True,
            ),
            _sahara(
                "Speaker 1",
                "Mention on the fourteenth of April twenty twenty-six at ten o'clock in the forenoon for directions and fixing of a hearing date. Pending that mention, the defendant shall continue paying the contractual monthly rent into court.",
                92,
                16,
                court=True,
            ),
            _sahara(
                "Speaker 2",
                "Much obliged, my lady. We will diarise the mention and update the client file.",
                108,
                7,
                court=True,
            ),
            _sahara(
                "Speaker 3",
                "As the court pleases. My lady, may we briefly address a scheduling matter off the record regarding a without-prejudice settlement discussion?",
                115,
                10,
                court=True,
            ),
            _sahara(
                "Speaker 1",
                "That exchange stays off the record. Hii ni amri ya mahakama as delivered. Court rises.",
                125,
                8,
                court=True,
            ),
        ],
        "redact_indexes": [11],
        "generate": True,
    },
    {
        "title": "Client intake — Bello Trading, Kano warehouse lease dispute",
        "source": "mic",
        "language_hint": "en-ha",
        "detected_language": "multilingual",
        "client_name": "Bello Trading Ltd",
        "speakers": {"Speaker 1": "Adv. Aisha Mohammed", "Speaker 2": "Alhaji Musa Bello"},
        "flags": [
            {"at_ms": 8000, "label": "Arrears claimed — NGN 8.4M"},
            {"at_ms": 56000, "label": "Fourteen-day demand before suit"},
        ],
        "segments": [
            _sahara(
                "Speaker 1",
                "Sannu da zuwa, Alhaji. Before we begin — this conversation is privileged. Tell me what happened with the Kano warehouse lease.",
                0,
                10,
            ),
            _sahara(
                "Speaker 2",
                "Nagode. Northern Logistics locked the gate on the third of September. They claim we owe eight point four million naira in arrears — gaskiya we dispute three months of service charge that was never billed properly.",
                10,
                15,
            ),
            _sahara(
                "Speaker 1",
                "Did they serve a written notice of re-entry before they padlocked the premises?",
                25,
                7,
            ),
            _sahara(
                "Speaker 2",
                "Only a WhatsApp message from their estate manager. No formal letter, no inventory taken with our representative. Lahiya ta yi for the staff, but our Abuja consignment is stuck inside.",
                32,
                14,
            ),
            _sahara(
                "Speaker 1",
                "Without proper notice, the lock-out is vulnerable. We will send a fourteen-day demand for restoration of possession and particularisation of the arrears, then move for an interim injunction in the High Court of Kano State if they refuse.",
                46,
                15,
            ),
            _sahara(
                "Speaker 2",
                "Alkali ya yi hukunci when we get there — we want possession restored first, then we can negotiate the disputed months. I can pay the undisputed rent into escrow.",
                61,
                12,
            ),
            _sahara(
                "Speaker 1",
                "That helps. Bring the lease, the payment schedule, photos of the lock-out, and the WhatsApp thread. Draft demand goes out by Friday.",
                73,
                11,
            ),
            _sahara(
                "Speaker 2",
                "One thing — keep the tax discussion with my partner about the side import invoices off this file. That one is sensitive.",
                84,
                10,
            ),
            _sahara(
                "Speaker 1",
                "Understood — that stays privileged. I will diarise a follow-up for next Tuesday at ten after you have sent the documents.",
                94,
                10,
            ),
            _sahara(
                "Speaker 2",
                "Nagode sosai. I will email everything this afternoon.",
                104,
                5,
            ),
            _sahara(
                "Speaker 1",
                "Good. Do not attempt to force the gate open. We proceed on paper first.",
                109,
                7,
            ),
        ],
        "redact_indexes": [7],
        "generate": True,
    },
    {
        "title": "Client call — Adeyemi & Co, Lagos employment notice review",
        "source": "omi",
        "language_hint": "en-yo",
        "detected_language": "multilingual",
        "client_name": "Adeyemi & Co",
        "speakers": {"Speaker 1": "Adv. Folake Adeyemi", "Speaker 2": "Tunde Okonkwo"},
        "flags": [
            {"at_ms": 9000, "label": "Termination without three months' notice"},
            {"at_ms": 72000, "label": "NICN filing if no settlement — 3 October"},
        ],
        "segments": [
            _sahara(
                "Speaker 1",
                "E kaabo, Tunde. This call is privileged. Jowo, walk me through the termination letter from your employer.",
                0,
                9,
            ),
            _sahara(
                "Speaker 2",
                "They terminated me on the twelfth without three months' notice in the contract. Salary arrears of two months dey, plus unpaid leave. I need a demand letter before we file at the National Industrial Court.",
                9,
                15,
            ),
            _sahara(
                "Speaker 1",
                "Was there a disciplinary hearing or a query before the letter?",
                24,
                6,
            ),
            _sahara(
                "Speaker 2",
                "Nothing. HR just sent the letter by email. My line manager said performance, but no appraisal was shared. Wetin we fit claim exactly?",
                30,
                12,
            ),
            _sahara(
                "Speaker 1",
                "We quantify three months' notice pay, the two months' salary arrears, leave, and damages for unfair dismissal. We give them twenty-one days to settle before we file at the National Industrial Court in Lagos.",
                42,
                15,
            ),
            _sahara(
                "Speaker 2",
                "O se. I will send the contract, payslips, and the termination email this evening. Keep the without-prejudice settlement talk I had with HR off anything you write — they offered a small package orally.",
                57,
                14,
            ),
            _sahara(
                "Speaker 1",
                "That stays off the record. Demand letter only uses the contractual figures. If they do not settle, we file. I will diarise the filing checkpoint for the third of October.",
                71,
                13,
            ),
            _sahara(
                "Speaker 2",
                "Perfect. Can we speak again once you have the draft?",
                84,
                5,
            ),
            _sahara(
                "Speaker 1",
                "Yes — Friday morning. Send the documents tonight and I will circulate the draft demand for your approval.",
                89,
                9,
            ),
        ],
        "redact_indexes": [5],
        "generate": True,
    },
    {
        "title": "Mention notes — Dlamini, Johannesburg eviction defence",
        "source": "mic",
        "language_hint": "en-zu",
        "detected_language": "multilingual",
        "client_name": "Thandi Dlamini",
        "speakers": {"Speaker 1": "Adv. Sipho Nkosi", "Speaker 2": "Thandi Dlamini"},
        "flags": [
            {"at_ms": 12000, "label": "Section 4 notice — service disputed"},
            {"at_ms": 48000, "label": "Interim stay application"},
        ],
        "segments": [
            _sahara(
                "Speaker 1",
                "Sawubona, Thandi. This conversation is privileged. The landlord seeks eviction from the Hillbrow flat — what notice did you receive?",
                0,
                11,
            ),
            _sahara(
                "Speaker 2",
                "Ngiyabonga, advocate. They taped a letter on the door only. No personal service, no sheriff. Rent is two months behind because of the factory shutdown, not because I refuse to pay.",
                11,
                15,
            ),
            _sahara(
                "Speaker 1",
                "Under PIE we can challenge defective service of the section four notice. Inkantolo must also see your payment history and the reason for the arrears.",
                26,
                12,
            ),
            _sahara(
                "Speaker 2",
                "I can pay half the arrears by Friday if they stop any lock-out. I still work night shifts — I need to stay in that flat until the factory takes me back.",
                38,
                12,
            ),
            _sahara(
                "Speaker 1",
                "We will apply for an interim stay at the Johannesburg Magistrates' Court and put a payment proposal on record. Bring bank statements and the taped notice photo.",
                50,
                13,
            ),
            _sahara(
                "Speaker 2",
                "Please keep my sister's medical situation out of any affidavit. That is family business, not for the landlord's attorneys.",
                63,
                10,
            ),
            _sahara(
                "Speaker 1",
                "Noted — that stays off the record. I will draft the stay papers, the answering affidavit on service, and diarise a return date for next Wednesday.",
                73,
                12,
            ),
            _sahara(
                "Speaker 2",
                "Ngiyezwa. I will WhatsApp the photos tonight and bring the statements tomorrow.",
                85,
                7,
            ),
            _sahara(
                "Speaker 1",
                "Good. Do not hand over keys and do not sign anything from the landlord without calling me first.",
                92,
                8,
            ),
        ],
        "redact_indexes": [5],
        "generate": True,
    },
]
