/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as SessionsSessionIdChatIndexRouteImport } from './routes/sessions_.$sessionId.chat.index'
import { Route as SessionsSessionIdChatThreadIdRouteImport } from './routes/sessions_.$sessionId.chat.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdChatIndexRoute =
  SessionsSessionIdChatIndexRouteImport.update({
    id: '/sessions_/$sessionId/chat/',
    path: '/sessions/$sessionId/chat/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionsSessionIdChatThreadIdRoute =
  SessionsSessionIdChatThreadIdRouteImport.update({
    id: '/sessions_/$sessionId/chat/$threadId',
    path: '/sessions/$sessionId/chat/$threadId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/tracker': typeof TrackerRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/$sessionId/chat/$threadId': typeof SessionsSessionIdChatThreadIdRoute
  '/sessions/$sessionId/chat/': typeof SessionsSessionIdChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/tracker': typeof TrackerRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/$sessionId/chat/$threadId': typeof SessionsSessionIdChatThreadIdRoute
  '/sessions/$sessionId/chat': typeof SessionsSessionIdChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/tracker': typeof TrackerRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions_/$sessionId/chat/$threadId': typeof SessionsSessionIdChatThreadIdRoute
  '/sessions_/$sessionId/chat/': typeof SessionsSessionIdChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connectors'
    | '/login'
    | '/new'
    | '/research'
    | '/settings'
    | '/tracker'
    | '/sessions/$sessionId'
    | '/sessions/$sessionId/chat/$threadId'
    | '/sessions/$sessionId/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connectors'
    | '/login'
    | '/new'
    | '/research'
    | '/settings'
    | '/tracker'
    | '/sessions/$sessionId'
    | '/sessions/$sessionId/chat/$threadId'
    | '/sessions/$sessionId/chat'
  id:
    | '__root__'
    | '/'
    | '/connectors'
    | '/login'
    | '/new'
    | '/research'
    | '/settings'
    | '/tracker'
    | '/sessions/$sessionId'
    | '/sessions_/$sessionId/chat/$threadId'
    | '/sessions_/$sessionId/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectorsRoute: typeof ConnectorsRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  ResearchRoute: typeof ResearchRoute
  SettingsRoute: typeof SettingsRoute
  TrackerRoute: typeof TrackerRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SessionsSessionIdChatThreadIdRoute: typeof SessionsSessionIdChatThreadIdRoute
  SessionsSessionIdChatIndexRoute: typeof SessionsSessionIdChatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions_/$sessionId/chat/': {
      id: '/sessions_/$sessionId/chat/'
      path: '/sessions/$sessionId/chat'
      fullPath: '/sessions/$sessionId/chat/'
      preLoaderRoute: typeof SessionsSessionIdChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions_/$sessionId/chat/$threadId': {
      id: '/sessions_/$sessionId/chat/$threadId'
      path: '/sessions/$sessionId/chat/$threadId'
      fullPath: '/sessions/$sessionId/chat/$threadId'
      preLoaderRoute: typeof SessionsSessionIdChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectorsRoute: ConnectorsRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  ResearchRoute: ResearchRoute,
  SettingsRoute: SettingsRoute,
  TrackerRoute: TrackerRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SessionsSessionIdChatThreadIdRoute: SessionsSessionIdChatThreadIdRoute,
  SessionsSessionIdChatIndexRoute: SessionsSessionIdChatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
